export const twUtils = {
  ".typography-H1-Bold": {
    fontFamily: "Inter",
    fontWeight: "Bold",
    lineHeight: "110%",
    fontSize: "78.126px",
    paragraphSpacing: "32px",
    letterSpacing: "-5%",
  },
  ".typography-H1-Regular": {
    fontFamily: "Inter",
    fontWeight: "Regular",
    lineHeight: "110%",
    fontSize: "78.126px",
    paragraphSpacing: "32px",
    letterSpacing: "-5%",
  },
  ".typography-H2-Bold": {
    fontFamily: "Inter",
    fontWeight: "Bold",
    lineHeight: "110%",
    fontSize: "39.063px",
    paragraphSpacing: "26px",
    letterSpacing: "-5%",
  },
  ".typography-H2-Regular": {
    fontFamily: "Inter",
    fontWeight: "Regular",
    lineHeight: "110%",
    fontSize: "39.063px",
    paragraphSpacing: "26px",
    letterSpacing: "-5%",
  },
  ".typography-Body": {
    fontFamily: "Roboto",
    fontWeight: "Regular",
    lineHeight: "110%",
    fontSize: "16px",
    paragraphSpacing: "26px",
  },
};
